spring:
  application:
    name:springboot-mybatis-quickstart
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/web
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

#Mybatis relative configuration
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml