spring:
  application:
    name: tlias-web-management
  #mysql connection configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 12345678
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl